"""
response_llm.py
---------------
LLM-based natural conversation response generator for the Lyra Agent.

Replaces template-based responses with a flowing, empathetic narrative
generated by the DeepSeek API.  Falls back to the template-based
``Response`` class on any failure.

Design principles
------------------
- **Same interface as Response.**  ``generate(user_input, intent, recommendations) -> str``
  — swapping implementations requires no changes to ``agent.py`` or ``main.py``.
- **Graceful degradation.**  If the API call fails for any reason
  (network, auth, parse error), the template-based fallback kicks in.
- **Lightweight.**  Low ``max_tokens`` and short timeout so the response
  stage adds minimal latency to the pipeline.
"""

import os
import time
from typing import Any, Dict, List

import requests
from dotenv import load_dotenv

from response import Response  # template-based fallback
from logger import get_logger

load_dotenv()

# ---------------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------------

RESPONSE_DEBUG = os.getenv("LYRA_RESPONSE_DEBUG", "0") == "1"
_log = get_logger("response", enabled=RESPONSE_DEBUG)

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "你是Lyra，一个温暖、善解人意的音乐推荐助手。\n"
    "你的回复风格：\n"
    "1. 像一个懂音乐、懂人心的朋友在聊天，不是客服，不是机器人。\n"
    "2. 先共情用户的情绪，用一两句温暖的话接住对方的心情。\n"
    "3. 自然地引出推荐，像在分享音乐而不是列清单。"
    "每首歌用1-2句话描述为什么适合对方，用优美但有温度的语言。\n"
    "4. 结尾送上一句温暖的话，让人感到被理解和陪伴。\n"
    "5. 不要使用markdown，不要编号列表，用自然的段落叙述。\n"
    "6. 回复长度控制在150-250字之间。"
)

USER_TEMPLATE = (
    "用户的原话：{user_input}\n"
    "系统识别到的情绪画像：{intent_summary}\n"
    "推荐的歌曲（已排序）：\n"
    "{recommendations}\n\n"
    "请用温暖、自然的语气回复用户，风格像朋友分享音乐。"
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

API_TEMPERATURE = 0.7  # slightly creative for natural conversation
API_MAX_TOKENS = 300
API_TIMEOUT = 8  # seconds — response should be fast


# ---------------------------------------------------------------------------
# LLMResponse
# ---------------------------------------------------------------------------


class LLMResponse:
    """LLM-based natural conversation response generator.

    Falls back to template-based ``Response`` on any failure, so the
    pipeline never breaks even if the API is unreachable.

    Usage::

        responder = LLMResponse()
        text = responder.generate(user_input, intent, recommendations)
    """

    def __init__(self, verbose: bool = None):
        self.api_key = os.getenv("DEEPSEEK_API_KEY", "")
        self.model = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")

        raw_base = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
        self.base_url = raw_base.rstrip("/")
        if not self.base_url.endswith("/v1"):
            self.base_url += "/v1"

        # When verbose is explicitly passed, override the module-level logger
        if verbose is not None:
            global _log
            from logger import Logger
            _log = Logger("response", enabled=verbose)

        self._fallback = Response()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        user_input: str,
        intent: Dict[str, Any],
        recommendations: List[Dict[str, Any]],
    ) -> str:
        """Generate a natural conversation response.

        Falls back to template-based generation on any failure.
        """
        try:
            return self._generate_llm(user_input, intent, recommendations)
        except Exception as exc:
            _log.warn(f"LLM generation failed ({exc}), falling back to templates")
            return self._fallback.generate(user_input, intent, recommendations)

    # ------------------------------------------------------------------
    # LLM generation
    # ------------------------------------------------------------------

    def _generate_llm(
        self,
        user_input: str,
        intent: Dict[str, Any],
        recommendations: List[Dict[str, Any]],
    ) -> str:
        """Call DeepSeek API for a natural, empathetic response."""
        intent_summary = self._build_intent_summary(intent)
        rec_text = self._build_recommendations_text(recommendations)

        user_message = USER_TEMPLATE.format(
            user_input=user_input,
            intent_summary=intent_summary,
            recommendations=rec_text,
        )

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
            "temperature": API_TEMPERATURE,
            "max_tokens": API_MAX_TOKENS,
        }

        url = f"{self.base_url}/chat/completions"

        _log.debug(f"→ API | model={self.model} | timeout={API_TIMEOUT}s")

        t0 = time.time()
        response = requests.post(
            url,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=API_TIMEOUT,
        )
        api_ms = (time.time() - t0) * 1000

        if response.status_code != 200:
            body_preview = response.text[:300]
            raise RuntimeError(
                f"Response API HTTP {response.status_code}: {body_preview}"
            )

        data = response.json()
        choices = data.get("choices", [])
        if not choices:
            raise RuntimeError(
                f"Response API returned no choices. Keys: {list(data.keys())}"
            )

        content = choices[0].get("message", {}).get("content", "")
        if not content:
            finish = choices[0].get("finish_reason", "unknown")
            raise RuntimeError(
                f"Response API returned empty content (finish_reason={finish})"
            )

        _log.debug(f"← API | {api_ms:.0f}ms | {len(content)} chars")

        return content.strip()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_intent_summary(intent: Dict[str, Any]) -> str:
        """Build a compact natural-language intent summary for the LLM prompt."""
        parts = []
        for field, label in [
            ("emotion", "情绪"),
            ("scene", "场景"),
            ("listener_need", "需求"),
        ]:
            val = intent.get(field, "")
            if isinstance(val, list):
                val = "、".join(val)
            if val and val != "（未识别）":
                parts.append(f"{label}: {val}")

        energy = intent.get("energy_level", "")
        if energy:
            energy_map = {"low": "安静舒缓", "medium": "中等节奏", "high": "高能量"}
            parts.append(f"能量偏好: {energy_map.get(energy, energy)}")

        avoid = intent.get("avoid", [])
        if avoid:
            parts.append(f"想避免: {'、'.join(avoid)}")

        return "; ".join(parts) if parts else "未识别"

    @staticmethod
    def _build_recommendations_text(recommendations: List[Dict]) -> str:
        """Format recommendations as compact text for the LLM prompt."""
        lines = []
        for i, rec in enumerate(recommendations, 1):
            title = rec.get("title", "?")
            artist = rec.get("artist", "?")
            reason = rec.get("reason", "")
            album = rec.get("album", "")
            year = rec.get("year", "")
            meta = f"{album} ({year})" if album else ""
            lines.append(
                f"{i}. 《{title}》— {artist}  {meta}\n"
                f"   推荐理由：{reason}"
            )
        return "\n".join(lines)
